# Generated by Django 2.2 on 2020-04-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_carrousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrousel',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
