# Generated by Django 2.2 on 2020-04-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200416_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrousel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
