# Generated by Django 2.2 on 2020-04-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_carrousel_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrousel',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='carrousel',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
