# Generated by Django 2.2 on 2020-04-17 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200416_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Lana'), ('SW', 'Sport Wear'), ('OW', 'Outwear')], default='S', max_length=2),
        ),
    ]
