# Generated by Django 2.2 on 2020-04-17 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200416_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='categori',
        ),
    ]
