# Generated by Django 2.2 on 2020-04-17 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_item_categori'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
