# Generated by Django 2.2 on 2020-04-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('S', 'Lana'), ('SW', 'Sport Wear'), ('OW', 'Outwear')], default='S', max_length=2, null=True),
        ),
    ]
