# Generated by Django 2.2 on 2020-04-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200416_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'Lan'), ('S', 'Lana'), ('SW', 'Sport Wear'), ('OW', 'Outwear')], max_length=2, null=True),
        ),
    ]
