# Generated by Django 2.2 on 2020-04-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_refound'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Refound',
            new_name='Refund',
        ),
    ]
