# Generated by Django 2.2 on 2020-04-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20200417_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrousel',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
