# Generated by Django 2.2 on 2020-04-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_carrousel_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrousel',
            name='link_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
