# Generated by Django 2.2 on 2020-04-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_carrousel_link_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='subtitle',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
